# Generated by Django 3.1.3 on 2020-11-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_body',
            field=models.TextField(max_length=200),
        ),
    ]
