# Generated by Django 3.1.3 on 2020-11-11 22:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201111_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
